LOCK TABLES `employee` WRITE;
/*!40000 ALTER TABLE `employee` DISABLE KEYS */;
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (1, 'Marie', 'Mandela', 'mmandela51@siwakadishes.co.ke', 6, 'Cook');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (2, 'Thabo', 'Mohammed', 'tmohammed24@siwakadishes.co.ke', 7, 'Waiter');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (3, 'Jean', 'Ndayishimiye', 'jndayishimiye12@siwakadishes.co.ke', 8, 'Hostess');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (4, 'Achieng', 'Hussein', 'ahussein16@siwakadishes.co.ke', 9, 'Security Guard');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (5, 'Jacqueline', 'Hussein', 'jhussein97@siwakadishes.co.ke', 8, 'Sous Chef');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (6, 'Patricia', 'Hassan', 'phassan43@siwakadishes.co.ke', 7, 'Dishwasher');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (7, 'Patricia', 'Kabila', 'pkabila52@siwakadishes.co.ke', 10, 'Cleaner');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (8, 'Jacqueline', 'Munyoki', 'jmunyoki19@siwakadishes.co.ke', 10, 'Manager');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (9, 'Patricia', 'Kabongo', 'pkabongo92@siwakadishes.co.ke', 4, 'Assistant Manager');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (10, 'Alain', 'Ibrahim', 'aibrahim84@siwakadishes.co.ke', 7, 'Host');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (11, 'Felix', 'Munyao', 'fmunyao90@siwakadishes.co.ke', 4, 'Manager');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (12, 'Wanjiku', 'Mugisha', 'wmugisha81@siwakadishes.co.ke', 9, 'Chef');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (13, 'Josephine', 'Munee', 'jmunee34@siwakadishes.co.ke', 1, 'Waiter');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (14, 'Ngozi', 'Mugisha', 'nmugisha12@siwakadishes.co.ke', 9, 'Waitress');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (15, 'Alaine', 'Kabila', 'akabila86@siwakadishes.co.ke', 2, 'Manager');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (16, 'Kiptoo', 'Mukasa', 'kmukasa79@siwakadishes.co.ke', 9, 'Waiter');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (17, 'Pierrette', 'Omondi', 'pomondi3@siwakadishes.co.ke', 2, 'Receptionist');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (18, 'Gbemisola', 'Bizimana', 'gbizimana23@siwakadishes.co.ke', 6, 'Manager');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (19, 'Adisa', 'Ochieng', 'aochieng30@siwakadishes.co.ke', 1, 'Cleaner');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (20, 'Patricia', 'Munywe', 'pmunywe20@siwakadishes.co.ke', 4, 'Bartender');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (21, 'Thabo', 'Lumumba', 'tlumumba27@siwakadishes.co.ke', 10, 'Cashier');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (22, 'Zanele', 'Ochieng', 'zochieng98@siwakadishes.co.ke', 9, 'Receptionist');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (23, 'Binta', 'Ndayishimiye', 'bndayishimiye21@siwakadishes.co.ke', 1, 'Cleaner');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (24, 'Michel', 'Mugabe', 'mmugabe59@siwakadishes.co.ke', 1, 'Chef');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (25, 'Emmanuel', 'Mbeki', 'embeki45@siwakadishes.co.ke', 2, 'Chef');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (26, 'Jean', 'Mandela', 'jmandela47@siwakadishes.co.ke', 4, 'Dishwasher');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (27, 'Dayo', 'Munyua', 'dmunyua2@siwakadishes.co.ke', 3, 'Dishwasher');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (28, 'Jacques', 'Njoroge', 'jnjoroge22@siwakadishes.co.ke', 2, 'Sous Chef');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (29, 'Otieno', 'Mandela', 'omandela41@siwakadishes.co.ke', 5, 'Waitress');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (30, 'Patricia', 'Mbeki', 'pmbeki71@siwakadishes.co.ke', 8, 'Cashier');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (31, 'Claudine', 'Kariuki', 'ckariuki45@siwakadishes.co.ke', 5, 'Waitress');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (32, 'Pauline', 'Abdi', 'pabdi4@siwakadishes.co.ke', 1, 'Manager');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (33, 'Dayo', 'Zuma', 'dzuma74@siwakadishes.co.ke', 10, 'Assistant Manager');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (34, 'Amina', 'Munyui', 'amunyui84@siwakadishes.co.ke', 5, 'Sous Chef');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (35, 'Ifeanyi', 'Ali', 'iali66@siwakadishes.co.ke', 9, 'Receptionist');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (36, 'Pauline', 'Munzala', 'pmunzala5@siwakadishes.co.ke', 9, 'Cook');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (37, 'Emmanuelle', 'Munzala', 'emunzala22@siwakadishes.co.ke', 9, 'Bartender');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (38, 'Gbemisola', 'Munzala', 'gmunzala3@siwakadishes.co.ke', 8, 'Cook');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (39, 'Femi', 'Abdullahi', 'fabdullahi14@siwakadishes.co.ke', 8, 'Waiter');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (40, 'Chiamaka', 'Munyui', 'cmunyui32@siwakadishes.co.ke', 10, 'Receptionist');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (41, 'Alaine', 'Mbeki', 'ambeki56@siwakadishes.co.ke', 1, 'Sous Chef');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (42, 'Mutiso', 'Munywe', 'mmunywe70@siwakadishes.co.ke', 7, 'Cook');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (43, 'Emmanuelle', 'Mandela', 'emandela87@siwakadishes.co.ke', 8, 'Sous Chef');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (44, 'Jeanne', 'Abdi', 'jabdi1@siwakadishes.co.ke', 7, 'Cook');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (45, 'Zanele', 'Ibrahim', 'zibrahim2@siwakadishes.co.ke', 5, 'Waitress');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (46, 'Emmanuel', 'Munzala', 'emunzala80@siwakadishes.co.ke', 6, 'Bartender');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (47, 'Jelani', 'Nkurunziza', 'jnkurunziza12@siwakadishes.co.ke', 10, 'Sous Chef');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (48, 'Marie', 'Mutua', 'mmutua21@siwakadishes.co.ke', 7, 'Waitress');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (49, 'Binta', 'Mbeki', 'bmbeki89@siwakadishes.co.ke', 1, 'Cook');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (50, 'Felicite', 'Adan', 'fadan91@siwakadishes.co.ke', 5, 'Assistant Manager');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (51, 'Jelani', 'Kagame', 'jkagame84@siwakadishes.co.ke', 10, 'Cashier');
INSERT INTO siwaka_dishes.employee (employeeNumber, firstName, lastName, email, branchCode, jobTitle) VALUES (52, 'Zanele', 'Munyao', 'zmunyao70@siwakadishes.co.ke', 4, 'Waiter');
UPDATE siwaka_dishes.employee SET reportsTo = 8 WHERE employeeNumber = 13;
UPDATE siwaka_dishes.employee SET reportsTo = 11 WHERE employeeNumber = 19;
UPDATE siwaka_dishes.employee SET reportsTo = 24 WHERE employeeNumber = 23;
UPDATE siwaka_dishes.employee SET reportsTo = 28 WHERE employeeNumber = 24;
UPDATE siwaka_dishes.employee SET reportsTo = 25 WHERE employeeNumber = 32;
UPDATE siwaka_dishes.employee SET reportsTo = 34 WHERE employeeNumber = 41;
UPDATE siwaka_dishes.employee SET reportsTo = 47 WHERE employeeNumber = 49;
UPDATE siwaka_dishes.employee SET reportsTo = 32 WHERE employeeNumber = 15;
UPDATE siwaka_dishes.employee SET reportsTo = 15 WHERE employeeNumber = 17;
UPDATE siwaka_dishes.employee SET reportsTo = 28 WHERE employeeNumber = 25;
UPDATE siwaka_dishes.employee SET reportsTo = 9 WHERE employeeNumber = 28;
UPDATE siwaka_dishes.employee SET reportsTo = 8 WHERE employeeNumber = 27;
UPDATE siwaka_dishes.employee SET reportsTo = 8 WHERE employeeNumber = 9;
UPDATE siwaka_dishes.employee SET reportsTo = 34 WHERE employeeNumber = 11;
UPDATE siwaka_dishes.employee SET reportsTo = 47 WHERE employeeNumber = 20;
UPDATE siwaka_dishes.employee SET reportsTo = 18 WHERE employeeNumber = 26;
UPDATE siwaka_dishes.employee SET reportsTo = 9 WHERE employeeNumber = 52;
UPDATE siwaka_dishes.employee SET reportsTo = 43 WHERE employeeNumber = 29;
UPDATE siwaka_dishes.employee SET reportsTo = 28 WHERE employeeNumber = 31;
UPDATE siwaka_dishes.employee SET reportsTo = 50 WHERE employeeNumber = 34;
UPDATE siwaka_dishes.employee SET reportsTo = 34 WHERE employeeNumber = 45;
UPDATE siwaka_dishes.employee SET reportsTo = 8 WHERE employeeNumber = 50;
UPDATE siwaka_dishes.employee SET reportsTo = 28 WHERE employeeNumber = 1;
UPDATE siwaka_dishes.employee SET reportsTo = 9 WHERE employeeNumber = 18;
UPDATE siwaka_dishes.employee SET reportsTo = 25 WHERE employeeNumber = 46;
UPDATE siwaka_dishes.employee SET reportsTo = 34 WHERE employeeNumber = 2;
UPDATE siwaka_dishes.employee SET reportsTo = 18 WHERE employeeNumber = 6;
UPDATE siwaka_dishes.employee SET reportsTo = 18 WHERE employeeNumber = 10;
UPDATE siwaka_dishes.employee SET reportsTo = 43 WHERE employeeNumber = 42;
UPDATE siwaka_dishes.employee SET reportsTo = 18 WHERE employeeNumber = 44;
UPDATE siwaka_dishes.employee SET reportsTo = 47 WHERE employeeNumber = 48;
UPDATE siwaka_dishes.employee SET reportsTo = 18 WHERE employeeNumber = 3;
UPDATE siwaka_dishes.employee SET reportsTo = 12 WHERE employeeNumber = 5;
UPDATE siwaka_dishes.employee SET reportsTo = 33 WHERE employeeNumber = 30;
UPDATE siwaka_dishes.employee SET reportsTo = 12 WHERE employeeNumber = 38;
UPDATE siwaka_dishes.employee SET reportsTo = 15 WHERE employeeNumber = 39;
UPDATE siwaka_dishes.employee SET reportsTo = 11 WHERE employeeNumber = 43;
UPDATE siwaka_dishes.employee SET reportsTo = 28 WHERE employeeNumber = 4;
UPDATE siwaka_dishes.employee SET reportsTo = 15 WHERE employeeNumber = 12;
UPDATE siwaka_dishes.employee SET reportsTo = 43 WHERE employeeNumber = 14;
UPDATE siwaka_dishes.employee SET reportsTo = 15 WHERE employeeNumber = 16;
UPDATE siwaka_dishes.employee SET reportsTo = 12 WHERE employeeNumber = 22;
UPDATE siwaka_dishes.employee SET reportsTo = 5 WHERE employeeNumber = 35;
UPDATE siwaka_dishes.employee SET reportsTo = 32 WHERE employeeNumber = 36;
UPDATE siwaka_dishes.employee SET reportsTo = 15 WHERE employeeNumber = 37;
UPDATE siwaka_dishes.employee SET reportsTo = 50 WHERE employeeNumber = 7;
UPDATE siwaka_dishes.employee SET reportsTo = 41 WHERE employeeNumber = 8;
UPDATE siwaka_dishes.employee SET reportsTo = 33 WHERE employeeNumber = 21;
UPDATE siwaka_dishes.employee SET reportsTo = 5 WHERE employeeNumber = 33;
UPDATE siwaka_dishes.employee SET reportsTo = 32 WHERE employeeNumber = 40;
UPDATE siwaka_dishes.employee SET reportsTo = 28 WHERE employeeNumber = 47;
UPDATE siwaka_dishes.employee SET reportsTo = 18 WHERE employeeNumber = 51;
/*!40000 ALTER TABLE `employee` ENABLE KEYS */;
UNLOCK TABLES;